<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.litterat.test.core.EmbeddedUnionTest" tests="4" skipped="0" failures="1" errors="0" timestamp="2025-01-02T01:06:28" hostname="Davids-MacBook-Air-2.local" time="0.009">
  <properties/>
  <testcase name="testMapToObjectException()" classname="io.litterat.test.core.EmbeddedUnionTest" time="0.002">
    <failure message="org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;io.litterat.core.TypeException&gt; but was: &lt;io.litterat.bind.DataBindException&gt;" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;io.litterat.core.TypeException&gt; but was: &lt;io.litterat.bind.DataBindException&gt;
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at app/io.litterat.test.core/io.litterat.test.core.EmbeddedUnionTest.testMapToObjectException(EmbeddedUnionTest.java:124)
	at java.base@23.0.1/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@23.0.1/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base@23.0.1/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: io.litterat.bind.DataBindException: Failed to convert class io.litterat.test.core.union.EmbeddedUnion to Map
	at app/io.litterat.bind/io.litterat.bind.mapper.MapMapper.toMap(MapMapper.java:115)
	at app/io.litterat.bind/io.litterat.bind.mapper.MapMapper.toMap(MapMapper.java:42)
	at app/io.litterat.test.core/io.litterat.test.core.EmbeddedUnionTest.lambda$testMapToObjectException$0(EmbeddedUnionTest.java:125)
	at app/org.junit.jupiter.api@5.11.4/org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more
Caused by: java.lang.RuntimeException: io.litterat.bind.DataBindException: Value 'java.lang.Long' not in valid types [java.lang.Integer, java.lang.String]
	at io.litterat.bind/io.litterat.bind.DataClassField.get(DataClassField.java:129)
	at io.litterat.bind/io.litterat.bind.mapper.MapMapper.toMap(MapMapper.java:69)
	... 9 more
Caused by: io.litterat.bind.DataBindException: Value 'java.lang.Long' not in valid types [java.lang.Integer, java.lang.String]
	at app/io.litterat.bind/io.litterat.bind.DataClassUnion.checkIsMember(DataClassUnion.java:115)
	at app/io.litterat.bind/io.litterat.bind.DataClassField.get(DataClassField.java:127)
	... 10 more
</failure>
  </testcase>
  <testcase name="testToArray()" classname="io.litterat.test.core.EmbeddedUnionTest" time="0.001"/>
  <testcase name="testToMap()" classname="io.litterat.test.core.EmbeddedUnionTest" time="0.002"/>
  <testcase name="checkDescriptor()" classname="io.litterat.test.core.EmbeddedUnionTest" time="0.002"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
